front/app/urls.py
from django.contrib import admin
from django.urls import path
from . import views
from .views import FrontViewSet

app_name='app'
urlpatterns = [
    path('addmap', views.addmap, name='addmap'),
    path('maps', FrontViewSet.as_view({
        'get': 'list',
    }), name='maps'),
    path('play', FrontViewSet.as_view({
        'get': 'play',
    }), name='play'),
    path('send', FrontViewSet.as_view({
        'post': 'send',
    }), name='send'),
    path('new/<int:map>', FrontViewSet.as_view({
        'get': 'new',
    }), name='new'),
    path('map_info/<int:map_id>', FrontViewSet.as_view({
        'get': 'map_info',
    }), name='map_info'),
    path('main', FrontViewSet.as_view({
        'get': 'index',
    }), name='index'),
    path('', FrontViewSet.as_view({
        'get': 'index',
    }), name='blank'),
    path('confirm', FrontViewSet.as_view({
        'post': 'confirm',
    }), name='confirm'),
    path('login', FrontViewSet.as_view({
        'get': 'login'
    }), name='login'),
    path('verify', FrontViewSet.as_view({
        'post': 'verify'
    }), name='verify'),
    path('register', FrontViewSet.as_view({
        'get': 'register'
    }), name='register'),
    path('verify_register', FrontViewSet.as_view({
        'post': 'verify_register'
    }), name='verify_register'),
    path('logout', FrontViewSet.as_view({
        'get': 'logout'
    }), name='logout'),
    path('user_info/<int:user_id>', FrontViewSet.as_view({
        'get': 'user_info'
    }), name='user_info'),
]

front/front/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    #path('admin/', admin.site.urls),
    path('', include('app.urls')),
]

front/app/views.py
import json
from django.shortcuts import render, redirect
import requests
from requests.api import head
from requests.models import Response
from rest_framework import viewsets
from django.http import HttpResponse
from rest_framework.response import Response as RResponse

# Create your views here.

def addmap(request):

	return render(request, 'addmap.html')

class FrontViewSet(viewsets.ViewSet):
	def list(self, request):

		if 'player_id' not in request.session:
			return redirect('/login')

		r=requests.get('http://10.56.4.216:8000/api/app?format=json')
		m = []
		for e in r.json():
			m.append(e['name'])
		context = {
			"maps" : r.json(),
		}
		return render(request, 'maps.html', context)

	def play(self, request):
		if 'player_id' not in request.session:
			return redirect('/login')

		r=requests.get('http://10.56.1.171:8000/play/' + str(request.session['player_id']))
		if r.status_code != 200:
			return redirect('/maps')
		response = r.json()
		if response['status'] == 'game_on':
			context = {
				'lat' : response['data']['lat'],
				'lng' : response['data']['lng'],
			}
			return render(request, 'play.html', context)
		if response['status'] == 'game_finished':
			context = {
				'distance' : response['result']
			}
			return render(request, 'finished.html', context)

		return RResponse(r.json())

	def send(self, request):
		if 'player_id' not in request.session:
			return redirect('/login')
		r=requests.post('http://10.56.1.171:8000/play/' + str(request.session['player_id']), data=json.dumps(request.data), headers={'content-type': 'application/json'})
		return RResponse(data=r.json())

	def new(self, request, map):
		if 'player_id' not in request.session:
			return redirect('/login')
		r=requests.get('http://10.56.1.171:8000/new/' + str(map) + '/' + str(request.session['player_id']))
		return redirect('/play')

	def index(self, request):
		if 'player_id' not in request.session:
			return redirect('/login')
		return render(request, 'index.html')

	def confirm(self, request):
		if 'player_id' not in request.session:
			return redirect('/login')

		data=json.dumps(request.data)
		r=requests.post(url='http://10.56.4.216:8000/api/app', data=data, headers={'content-type': 'application/json'})
		return render(request, 'index.html') #cokolwiek
	
	def login(self, request):
		return render(request, 'login.html')
	
	def verify(self, request):
		dict = {}
		dict['name'] = request.POST['name']
		dict['password'] = request.POST['password']
		data = json.dumps(dict)
		r=requests.get(url='http://10.56.7.90:8000/login', data=data, headers={'content-type': 'application/json'})
		if r.status_code != 200:
			return redirect('/login') 
		data = json.loads(r.json())
		request.session['player_id'] = data['id']
		return redirect('/main')

	def register(self, request):
		return render(request, 'register.html')
	
	def verify_register(self, request):
		name = request.POST['name']
		password = request.POST['password']
		rep = request.POST['rep']
		if password != rep or len(password) < 3 or len(name) < 3:
			return redirect('/register')
		
		dict = {}
		dict['name'] = name
		dict['password'] = password 
		data = json.dumps(dict)
		r=requests.get(url='http://10.56.7.90:8000/register', data=data, headers={'content-type': 'application/json'})
		if r.status_code != 200:
			return redirect('/register') 
		return redirect('/main')
	
	def logout(self, request):
		if 'player_id' in request.session:
			del request.session['player_id']
		return redirect('/main')

	
	def map_info(self, request, map_id):
		if 'player_id' not in request.session:
			return redirect('/login')

		r=requests.get(url='http://10.56.4.216:8000/api/details/' + str(map_id))
		if r.status_code != 200:
			return redirect('/main')
		data = r.json()

		user_ids = []
		for stat in data:
			user_ids.append(stat['user_id'])

		r=requests.get(url='http://10.56.7.90:8000/user_names', data=json.dumps(user_ids), headers={'content-type': 'application/json'})
		dict = json.loads(r.json())
		for i in range(0, len(data)):
			data[i]['username'] = dict[i]

		context = {
			'stats': data
		}
		return render(request, 'details.html', context)


	def user_info(self, request, user_id):
		if 'player_id' not in request.session:
			return redirect('/login')
		
		r=requests.get(url='http://10.56.7.90:8000/user_info/'+str(user_id))
		if r.status_code != 200:
			return redirect('/main')
		context = {
			'info': r.json()
		}
		return render(request, 'user_info.html', context)
		

front/app/templates/addmap.html
{% load static %}
<!DOCTYPE html>
<html>
  <head>
    <title>Street View split-map-panes</title>
    <script type="text/javascript" src={% static 'js/scripts.js' %}></script>
    <script src="https://polyfill.io/v3/polyfill.min.js?features=default"></script>
    <style type="text/css">
      html,
      body {
        height: 100%;
        margin: 0;
        padding: 0;
      }

      #map,
      #pano {
        float: left;
        height: 100%;
        width: 50%;
      }
      #add {
        padding: 0;
        border: 1;
        position: absolute;
        top: 90vh;
        left: 5vw;
        z-index: 1;
        height: 30px;
        width: 200px;
      }
      #send {
        padding: 0;
        border: 0;
        position: absolute;
        top: 90vh;
        left: 30vw;
        z-index: 1;
        height: 30px;
        width: 300px;
      }
      #name {
        padding: 0;
        border: 1;
        z-index: 1;
        height: 26px;
        width: 200px;
      }
      #sbutton {
        padding: 0;
        border: 1;
        z-index: 1;
        height: 30px;
        width: 50px;
      }

    </style>
  </head>
  <body>
    <button id="add" type="button" onclick="add()">ADD</button>
    <div id="send">
      <input type="text" id="name"></input>
      <button id="sbutton" type="button" onclick="send()">SEND</button>
    </div>
    <div id="map"></div>
    <div id="pano"></div>

    <!-- Async script executes immediately and must be after any DOM elements used in callback. -->
    <script
      src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDukeE2EPVb-eRGltH24IL8KUXm4ysuwe0&callback=initialize&libraries=&v=weekly"
      async
    ></script>
	<div id="coords"></div>
  </body>
</html>

front/app/templates/details.html
<ul>
{% for s in stats %}
<li><a href="{%url 'app:user_info' s.user_id %}">{{s.username}}</a>: {{s.highscore}}</li>
{% endfor %}
</ul>

front/app/templates/finished.html
{% load static %}
<!DOCTYPE html>
<html>
  <head>
    <script>
        function next() {
            window.location.replace("/maps");
        }
    </script>
    <style type="text/css">
      body {
        font-size: 8vh;
        height: 100%;
        margin: 0;
        padding: 0;
        text-align: center;
      }
      #next {
        font-size: 10vh;
        height: 30vh;
        width: 60vw;
      }

    </style>
  </head>
  <body>
    Final score: {{distance}} metres.
    <button id="next" type="button" onclick="next()">PLAY AGAIN</button>
  </body>
</html>

front/app/templates/index.html
{% load static %}
<link rel="shortcut icon" type="image/png" href="{% static 'favicon.ico' %}"/>
<a href='/logout'>Log out</a><br>
<a href='/maps'>Maps</a><br>
<a href='/addmap'>Add map</a>

front/app/templates/login.html
{% load static %}
<!DOCTYPE html>
<html>
  <head></head>
  <body>
      <a href="{% url 'app:register' %}">Register</a><br>
      <h1>Log in</h1>
      <form action="{% url 'app:verify' %}" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <label>Username</label>
        <input type="text" name="name"> <br>
        <label>Password</label>
        <input type="password" name="password"> <br>
        <input type="submit" value="LOG IN"> <br>
      </form>
  </body>
</html>

front/app/templates/maps.html
<html>
    <head>
        <style type='text/css'>
            body {
                background-color: lightgrey;
                font-family: "Courier New", monospace;
            }
            .map {
                background-color: white;
                height: 60px;
                width: auto;
                margin: 10px;
                padding: 10px;
                float: left;
                font-size: 40px;
            }
            .play {
                background-color: lightgrey;
                height: auto;
                width: auto;
                margin: 2px;
                padding: 2px;
                float: right;
                font-size: 40px;
            }
            .map:hover {
                background-color: rgb(224, 224, 224);
            }
        </style>
    </head>
    <body>
        {% for m in maps %}
        <div class="map">
            {{m.name}}
            <div class="play" onclick="window.location.replace('/new/{{m.id}}')">
                PLAY
            </div>
            <div class="play" onclick="window.location.replace('/map_info/{{m.id}}')">
                SCORES
            </div>
        </div>
        {% endfor %}
    </body>
</html>

front/app/templates/play.html
{% load static %}
<!DOCTYPE html>
<html>
  <head>
    <title>Street View split-map-panes</title>
    <script>
      let panorama;
      let map;
      let marker;
      let latlng = { lat: 52.211916160272324, lng: 20.98251877698795};
      var json = {};
          
      function processSVData(data, status) {
          if (status === "OK") {
              const location = data.location;
              latLng = location.latLng;
              marker.setPosition(location.latLng);
              panorama.setPano(location.pano);
              panorama.setPov({
                  heading: 270,
                  pitch: 0,
              });
              panorama.setVisible(true);
          } else {
              console.error("Street View data not found for this location.");
          }
      }
      
      function initialize() {
          const loc = { lat: parseFloat('{{lat}}'), lng: parseFloat('{{lng}}')};
          const mimuw = { lat: 52.211916160272324, lng: 20.98251877698795};
          const sv = new google.maps.StreetViewService();
      
          map = new google.maps.Map(document.getElementById("map"), {
              center: mimuw,
              zoom: 14,
              disableDefaultUI: true,
              clickableIcons: false,
          });
        
          panorama = new google.maps.StreetViewPanorama(
              document.getElementById("pano"),
              {
                  position: loc,
                  pov: {
                      heading: 34,
                      pitch: 10,
                  },
                  disableDefaultUI: true,
                  showRoadLabels: false,
              }
          );
            
          marker = new google.maps.Marker({
              position: mimuw,
              icon: {
                url: "{% static 'answer.png' %}",
                anchor: new google.maps.Point(22, 22),
              },
              map,
          });
          
          //map.setStreetView(panorama);
          map.addListener("click", (event) => {
              //sv.getPanorama({ location: event.latLng, radius: 50 }, processSVData);
              latLng = event.latLng;
              marker.setPosition(event.latLng);
          });
      }

      function showAnswer(data) {
        document.getElementById("content").innerHTML = '<div id="map2"></div><button id="next" onclick="next()">NEXT</button>'
        map = new google.maps.Map(document.getElementById("map2"), {
          center: {lat: data.elat, lng: data.elng},
          zoom: 17,
          disableDefaultUI: true,
          clickableIcons: false,
        });
        marker = new google.maps.Marker({
          position: {lat: data.elat, lng: data.elng},
          icon: {
            url: "{% static 'correct.png' %}",
            anchor: new google.maps.Point(22, 22),
          },
          map,
        });
        let marker2 = new google.maps.Marker({
            position: {lat: data.lat, lng: data.lng},
            icon: {
              url: "{% static 'answer.png' %}",
              anchor: new google.maps.Point(22, 22),
            },
            map,
        });
      }

      function next() {
        window.location.replace("/play");
      }

      function send() {
          json = { "lat": latLng.lat(), "lng": latLng.lng()}
          var xhr = new XMLHttpRequest();
          xhr.onreadystatechange = function() {
            if(xhr.readyState === XMLHttpRequest.DONE) {
              var status = xhr.status;
              if (status === 0 || (status >= 200 && status < 400)) {
                // The request has been completed successfully
                showAnswer(JSON.parse(xhr.responseText))
                //window.location.replace("/play");
              } else {
                // Oh no! There has been an error with the request!
              }
            }
          }
          var url = "/send";
          xhr.open("POST", url);
          xhr.setRequestHeader("Content-Type", "application/json");
          xhr.send(JSON.stringify(json));
      }
      
    </script>
    <!--<script src="https://polyfill.io/v3/polyfill.min.js?features=default"></script>-->
    <style type="text/css">
      html,
      body {
        height: 100%;
        margin: 0;
        padding: 0;
      }

      #content {
        height: 100%;
        width: 100%;
      }
      #left {
        float: left;
        height: 100%;
        width: 50%;
      }
      #answer {
        padding: 3vh 3vw;
        display: inline-block;
        text-decoration: none;
        background-color: #DDD; /* Green */
        height: 20%;
        width: 100%;
      }
      #next {
        padding: 3vh 3vw;
        display: inline-block;
        text-decoration: none;
        background-color: #DDD; /* Green */
        height: 20%;
        width: 100%;
      }

      #map {
        float: left;
        height: 80%;
        width: 100%;
      }
      #map2 {
        float: left;
        height: 80%;
        width: 100%;
      }
      #pano {
        float: right;
        height: 100%;
        width: 50%;
      }
      #result {
        height: 80%;
        width: 100%;
      }
    </style>
  </head>
  <body>
    <!--
    <input type="text" id="name">test</input>
    <button type="button" onclick="send()">SEND</button>
    -->

    <div id="content">
      <div id="left">
        <div id="map"></div>
        
        <button id="answer" onclick="send()">ANSWER</button>
      </div>
      <div id="pano"></div>
    </div>

    <!-- Async script executes immediately and must be after any DOM elements used in callback. -->
    <script
      src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDukeE2EPVb-eRGltH24IL8KUXm4ysuwe0&callback=initialize&libraries=&v=weekly"
      async
    ></script>
  </body>
</html>

front/app/templates/register.html
{% load static %}
<!DOCTYPE html>
<html>
  <head></head>
  <body>
      <h1>Log in</h1>
      <form action="{% url 'app:verify_register' %}" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <label>Username</label>
        <input type="text" name="name"> <br>
        <label>Password</label>
        <input type="password" name="password"> <br>
        <label>Confirm password</label>
        <input type="password" name="rep"> <br>
        <input type="submit" value="REGISTER">
      </form>
  </body>
</html>

front/app/templates/user_info.html
{% load static %}
<!DOCTYPE html>
<html>
  <body>
    <h1>{{info.name}}</h1>
    <ul>
      <li>Joined: {{info.joinDate}}</li>
      <li>Games played: {{info.gamesPlayed}}</li>
      <li>Average score: {{info.averageScore}}</li>
    </ul>
  </body>
</html>